_wandb:
    value:
        cli_version: 0.20.1
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
        python_version: 3.12.2
        t:
            "1":
                - 1
                - 9
                - 41
                - 103
            "2":
                - 1
                - 9
                - 41
                - 103
            "3":
                - 7
                - 13
                - 55
                - 66
            "4": 3.12.2
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
alpha:
    value: 0.3
dropout_p:
    value: 0.2
embed_dim:
    value: 128
lr:
    value: 0.0001
num_heads:
    value: 4
num_layers:
    value: 4
pos_weight:
    value: 25
