_wandb:
    value:
        cli_version: 0.20.1
        m:
            - "1": epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": val_auc
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_loss_epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_loss_step
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.12.2
        t:
            "1":
                - 1
                - 9
                - 41
                - 103
            "2":
                - 1
                - 9
                - 41
                - 103
            "3":
                - 7
                - 13
                - 55
                - 66
            "4": 3.12.2
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
alpha:
    value: 0.7
dropout:
    value: 0.15
lr:
    value: 0.0001
lstm_hidden:
    value: 256
lstm_layers:
    value: 1
pos_weight:
    value: 25
